from server.Utilities.MotorPorts import MotorPorts

HALF_BYTE = 128

# Drivetrain
RIGHT_FRONT_PORTS = MotorPorts(17, 27, 12)
RIGHT_REAR_PORTS = MotorPorts(9, 11, 18)
LEFT_FRONT_PORTS = MotorPorts(22, 10, 13)
LEFT_REAR_PORTS = MotorPorts(8, 7, 19)
LEFT_X_COFFICIENT = 1.1
DRIVE_FORWARD_SPEED = 0.2
DISTANCE_FROM_PLANT = 0
MAX_SEARCHING_PLANT_TIME = 0
ROTATION_SPEED = 0.2

# 4 ultrasonic sensors
COMMON_SONIC_TRIG = 4
RIGHT_SONIC_ECHO = 6
LEFT_SONIC_ECHO = 25
FRONT_SONIC_TRIG = 5

# Arm
SERVO_PORT = 18
OPENED_ARM_ANGLE = 90
CLOSED_ARM_ANGLE = 0
HUMIDITY_SENSOR_PORT = 19

# Elevator
ELEVATOR_RIGHT_PORTS = MotorPorts(20, 21, 12)
ELEVATOR_LEFT_PORTS = MotorPorts(26, 16, 13)
ELEVATOR_OPEN_SPEED = 0.3
ELEVATOR_OPEN_TIME = 3.0  # In seconds
ELEVATOR_CLOSE_SPEED = 0.3
ELEVATOR_CLOSE_TIME = 3.0  # In seconds

# Camera
CAMERA_PORT = 0
CAMERA_FPS = 20.0
CAMERA_RESOLUTION = (640, 360)

# IMU
IMU_BUS = 0
IMU_ADDRESS = 0

#DB
FB_URL = "https://greenbot-2d29c-default-rtdb.firebaseio.com/"