import MotorPorts

LEFT_X_COFFICIENT = 1.1
HALF_BYTE = 128

# motor ports define
RIGHT_FRONT_PORTS = MotorPorts(0, 0, 0)
RIGHT_REAR_PORTS = MotorPorts(0, 0, 0)
LEFT_FRONT_PORTS = MotorPorts(0, 0, 0)
LEFT_REAR_PORTS = MotorPorts(0, 0, 0)
SERVO_PORT = 0

# 4 ultrasonic sensors
FRONT_SONIC_TRIG = 17
FRONT_SONIC_ECHO = 18

RIGHT_SONIC_TRIG = 22
RIGHT_SONIC_ECHO = 23

LEFT_SONIC_TRIG = 24
LEFT_SONIC_ECHO = 25

REAR_SONIC_TRIG = 27
REAR_SONIC_ECHO = 4

SONIC =[(FRONT_SONIC_TRIG, FRONT_SONIC_ECHO), (RIGHT_SONIC_TRIG, RIGHT_SONIC_ECHO), (LEFT_SONIC_TRIG, LEFT_SONIC_ECHO), (REAR_SONIC_TRIG, REAR_SONIC_ECHO)]

HUMIDITY_SENSOR_PORT = 0